// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlm1FuW9H1LrOoMybhIuaNPiIVnFFjN74',
    appId: '1:899228549701:web:b0d0c52ae7c1decb84d92c',
    messagingSenderId: '899228549701',
    projectId: 'whatsapp-5ac10',
    authDomain: 'whatsapp-5ac10.firebaseapp.com',
    storageBucket: 'whatsapp-5ac10.appspot.com',
    measurementId: 'G-4H5QVJ3759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnQDvGRA3jnm6_cpYqNubt_wJd9MDB0Bs',
    appId: '1:899228549701:android:5f4a9f159b24722b84d92c',
    messagingSenderId: '899228549701',
    projectId: 'whatsapp-5ac10',
    storageBucket: 'whatsapp-5ac10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMu5rgqlu9Q0-CuiOyIPHkxErAMbQH9dc',
    appId: '1:899228549701:ios:396f1253452b31ee84d92c',
    messagingSenderId: '899228549701',
    projectId: 'whatsapp-5ac10',
    storageBucket: 'whatsapp-5ac10.appspot.com',
    iosClientId: '899228549701-v157ovq3gru0l6o470jk2pitve4kp954.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
